name: Prints a message every 15

on:
  schedule:
    - cron: '*/15 * * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print a message
        run: echo "Hello World!"
