name: Prints a message every 5 minutes

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print a message
        run: echo "Hello World!"
